package com.taotao.sso.pojo;
// Generated 2018-2-2 22:22:29 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * TbUser generated by hbm2java
 */
public class TbUser implements java.io.Serializable {

	private Long id;
	private String username;
	private String password;
	private String phone;
	private String email;
	private Date created;
	private Date updated;

	public TbUser() {
	}

	public TbUser(String username, String password, Date created, Date updated) {
		this.username = username;
		this.password = password;
		this.created = created;
		this.updated = updated;
	}

	public TbUser(String username, String password, String phone, String email, Date created, Date updated) {
		this.username = username;
		this.password = password;
		this.phone = phone;
		this.email = email;
		this.created = created;
		this.updated = updated;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
