package com.taotao.pojo;
// Generated 2018-2-2 22:22:29 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * TbContent generated by hbm2java
 */
public class TbContent implements java.io.Serializable {

	private Long id;
	private long categoryId;
	private String title;
	private String subTitle;
	private String titleDesc;
	private String url;
	private String pic;
	private String pic2;
	private String content;
	private Date created;
	private Date updated;

	public TbContent() {
	}

	public TbContent(long categoryId) {
		this.categoryId = categoryId;
	}

	public TbContent(long categoryId, String title, String subTitle, String titleDesc, String url, String pic,
			String pic2, String content, Date created, Date updated) {
		this.categoryId = categoryId;
		this.title = title;
		this.subTitle = subTitle;
		this.titleDesc = titleDesc;
		this.url = url;
		this.pic = pic;
		this.pic2 = pic2;
		this.content = content;
		this.created = created;
		this.updated = updated;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSubTitle() {
		return this.subTitle;
	}

	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}

	public String getTitleDesc() {
		return this.titleDesc;
	}

	public void setTitleDesc(String titleDesc) {
		this.titleDesc = titleDesc;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getPic() {
		return this.pic;
	}

	public void setPic(String pic) {
		this.pic = pic;
	}

	public String getPic2() {
		return this.pic2;
	}

	public void setPic2(String pic2) {
		this.pic2 = pic2;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
