package com.taotao.pojo;
// Generated 2018-2-2 22:22:29 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * TbItemParamItem generated by hbm2java
 */
public class TbItemParamItem implements java.io.Serializable {

	private Long id;
	private Long itemId;
	private String paramData;
	private Date created;
	private Date updated;

	public TbItemParamItem() {
	}

	public TbItemParamItem(Long itemId, String paramData, Date created, Date updated) {
		this.itemId = itemId;
		this.paramData = paramData;
		this.created = created;
		this.updated = updated;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getItemId() {
		return this.itemId;
	}

	public void setItemId(Long itemId) {
		this.itemId = itemId;
	}

	public String getParamData() {
		return this.paramData;
	}

	public void setParamData(String paramData) {
		this.paramData = paramData;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
