package com.taotao.search.pojo;
// Generated 2018-2-2 22:22:29 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * TbItem generated by hbm2java
 */
public class TbItem implements java.io.Serializable {

	private long id;
	private String title;
	private String sellPoint;
	private long price;
	private int num;
	private String barcode;
	private String image;
	private long cid;
	private byte status;
	private Date created;
	private Date updated;

	public TbItem() {
	}

	public TbItem(long id, String title, long price, int num, long cid, byte status, Date created, Date updated) {
		this.id = id;
		this.title = title;
		this.price = price;
		this.num = num;
		this.cid = cid;
		this.status = status;
		this.created = created;
		this.updated = updated;
	}

	public TbItem(long id, String title, String sellPoint, long price, int num, String barcode, String image, long cid,
			byte status, Date created, Date updated) {
		this.id = id;
		this.title = title;
		this.sellPoint = sellPoint;
		this.price = price;
		this.num = num;
		this.barcode = barcode;
		this.image = image;
		this.cid = cid;
		this.status = status;
		this.created = created;
		this.updated = updated;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSellPoint() {
		return this.sellPoint;
	}

	public void setSellPoint(String sellPoint) {
		this.sellPoint = sellPoint;
	}

	public long getPrice() {
		return this.price;
	}

	public void setPrice(long price) {
		this.price = price;
	}

	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public long getCid() {
		return this.cid;
	}

	public void setCid(long cid) {
		this.cid = cid;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
